services:
    # Le Backend (FastAPI + ORM + SQLite)
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: hardware-backend
        ports:
            - "5000:5000" # API accessible sur le port 5000
        volumes:
            - ./data:/app/data
            - ./backend:/app # Donne accès aux fichiers KiCad, au bom.csv et à la BDD sourcing.db
        restart: unless-stopped

    # Le Frontend
    frontend:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./frontend:/usr/share/nginx/html
            - ./data/uploads:/usr/share/nginx/html/uploads
            - ./data/hardware:/usr/share/nginx/html/hardware # Donne accès aux fichiers KiBot dans http://localhost:8080/data/
